### PR TITLE
run_qemu.sh: make ndctl compilation compatible with mkosi v15+ 

### PR DESCRIPTION
**Pull request by marc-hb**
6 commits. Some finer-grained testing in #78

### CODE REVIEW

**Comment by marc-hb** [comment]
Both 22.04 and 24.04 building ndctl now
https://github.com/pmem/run_qemu/actions/runs/12306102075/job/34347115663?pr=80

**Comment by marc-hb** [comment]
Really weird error in https://github.com/pmem/run_qemu/actions/runs/12306483889/job/34348289945?pr=80, looks like a glitch...
```
‣ Running second (final) stage…
‣  Basing off cached image root.img.cache-pre-inst
‣  Copied cached image as /home/runner/work/run_qemu/run_qemu/kernel/qbuild/.mkosi-ge6d__zg
‣  Refreshing partition table…
Partition #1 contains a vfat signature.
Partition #2 contains a ext4 signature.
‣  Refreshed partition table.
‣  Attaching /home/runner/work/run_qemu/run_qemu/kernel/qbuild/.mkosi-ge6d__zg as loopback…
‣  Attached /dev/loop3
‣  Refreshing file system /dev/loop3p2…
tune2fs 1.46.5 (30-Dec-2021)
This operation requires a freshly checked filesystem.
Please run e2fsck -f on the filesystem.
‣  (Detaching /dev/loop3)
```

**Comment by stellarhopper** [comment]
> Really weird error in https://github.com/pmem/run_qemu/actions/runs/12306483889/job/34348289945?pr=80, looks like a glitch...
> 
> ```
> ‣ Running second (final) stage…
> ‣  Basing off cached image root.img.cache-pre-inst
> ‣  Copied cached image as /home/runner/work/run_qemu/run_qemu/kernel/qbuild/.mkosi-ge6d__zg
> ‣  Refreshing partition table…
> Partition #1 contains a vfat signature.
> Partition #2 contains a ext4 signature.
> ‣  Refreshed partition table.
> ‣  Attaching /home/runner/work/run_qemu/run_qemu/kernel/qbuild/.mkosi-ge6d__zg as loopback…
> ‣  Attached /dev/loop3
> ‣  Refreshing file system /dev/loop3p2…
> tune2fs 1.46.5 (30-Dec-2021)
> This operation requires a freshly checked filesystem.
> Please run e2fsck -f on the filesystem.
> ‣  (Detaching /dev/loop3)
> ```

Yesh we've seen this infrequently in the past, must have to do with certain versions of mkosi and/or filesystem tooling - hasn't appeared in a while (over a year I'd say), and yeah the solution was to just rebuild the image.

**Review by stellarhopper — CHANGES_REQUESTED** [review]
s/ndclt/ndctl/ in commit message

**Comment by stellarhopper** [comment]
Otherwise, tested on Fedora 40 with both mkosi14, and mkosi 22, and both look good!

**Comment by marc-hb** [comment]
> s/ndclt/ndctl/ in the commit message body for "run_qemu.sh: do not silently fail to compile missing ndctl/"

Should be good now. 

(Zero code change)

**Review by stellarhopper — APPROVED** [review]

**Pull request merged**
