### PR TITLE
mkosi.conf fixes to prepare for v15. Bump required version to v11

### PR DESCRIPTION
**Pull request by marc-hb**
Again this is still a bit far from achieving compatibility with mkosi v15 but this time it's a major step forward - and this should have zero effect on v14 users for now.

See commit messages.

### CODE REVIEW

**Comment by marc-hb** [comment]
> and this should have zero effect on v14 users for now.

Would be great if someone can fetch and confirm.

**Comment by marc-hb** [comment]
Great news: I just booted an image built using mkosi v15 and v24 thanks to this PR + a few additional hacks! Even better: the _same_ hacks work for both v15 and v24, no configuration change needed between the two. At least none needed to just boot.

Caveat: this was achieved on Arch, not Fedora. Just because my Arch system is 10 times faster which makes me 10 times faster.

I tried this PR on Ubuntu too and it seems to work too! However it does not seem possible to run qemu inside my Ubuntu VM:

```
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize kvm: No such file or directory
```
Too many layers of emulation? I digress.

**Review by stellarhopper — COMMENTED** [review]
Does the move to [Content] break mkosi < 15, or do versions 11+ still comprehend that section?

**Review by stellarhopper — APPROVED** [review]

**Review by stellarhopper — APPROVED** [review]

**Review by stellarhopper — APPROVED** [review]

**Review by stellarhopper — APPROVED** [review]

**Comment by marc-hb** [comment]
> Does the move to [Content] break mkosi < 15, or do versions 11+ still comprehend that section?

No, see references in the corresponding message. v11+ should still work. I only tested v14 though.

**Comment by marc-hb** [comment]
> No, see references in the ~corresponding commit message~.

... in the comment in the source.

**Comment by stellarhopper** [comment]
Ah I see the comment now, looks good - giving it a quick test and if I don't run into anything I can merge these.

**Comment by stellarhopper** [comment]
Since mkosi.default isn't a thing for newer versions, it may be worth renaming `mkosi.<distro>.default.tmpl` to something a bit simpler and more readable - like `mkosi.conf.<distro>` (also since the templating now happens in the generic one)

**Comment by marc-hb** [comment]
> it may be worth renaming mkosi.<distro>.default.tmpl to something a bit simpler and more readable - like mkosi.conf.<distro> (also since the templating now happens in the generic one)

Sounds good but I'd rather do this after the de-duplication in this PR.

There are more PRs coming, I'm not going away soon :-)

**Comment by miguelinux** [comment]
my apologies for been late here @stellarhopper 

looks good your changes @marc-hb, and thanks for this contributions

**Pull request merged**
